version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.0-browsers
    steps:
      - checkout
      - restore_cache:
          key: ci2s3-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: ci2s3-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - run: npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
      - run: npm run build -- --prod
      - run: ls
