version: 2.1

orbs:
    aws-s3: circleci/aws-s3@1.0.0 #imports the s3 orb in the circleci namespace

jobs:
  build:
    docker:
      - image: circleci/node:10.15.0-browsers
    steps:
      - checkout
      - restore_cache:
          key: ci2s3-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: ci2s3-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run build -- --prod
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project
  test:
    docker:
      - image: circleci/node:10.15.0-browsers
    steps:
      - run: pwd
      - attach_workspace:
          at: /home/circleci
      - run: ls
      - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - run: npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js

  deploy:
    docker:
      - image: 'circleci/python:2.7'
    steps:
      - attach_workspace:
          at: /home/circleci
      - aws-s3/sync: #invokes the sync command declared in the s3 orb
          from: ./dist
          to: "s3://${S3_BUCKET}"

workflows:
  version: 2.1

  btd:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
