version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.0-browsers
    steps:
      - checkout
      - run: pwd
      - run: ls
      # - run:
      #     name: Install dependencies
      #     command: sudo npm install -g @angular/cli
      # - run:
      #     name: Version of angular
      #     command: ng version
