version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.0-browsers
    steps:
      - run:
          name: Install angular cli
          command: sudo npm install -g @angular/cli
      - run:
          name: List angular package versions
          command: ng version
      - checkout
      - run:
          name: Install app dependencies
          command: sudo npm install
      - run:
          name: install node-sass
          command: sudo npm install -g --unsafe-perm node-sass
      - run:
          name: Build app
          command: ng build --prod
