version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.0-browsers
    steps:
      - run:
          name: Install dependencies
          command: sudo npm install
      - run:
          name: List angular package versions
          command: ng version
      - checkout
      - run:
          name: Build app
          command: ng build
